### ISSUE TITLE
expected class or package:  flowLayoutManager.InsetDecoration

### ISSUE THREAD

**Issue by conanchen** [ch4vi/FlowLayout#1]
I have below java code as FlowLayout Readme says: 

FlowLayoutManager flowLayoutManager =new FlowLayoutManager(spanCount,RecyclerView.VERTICAL,new Interface(){...});

mRecyclerView.addItemDecoration(flowLayoutManager.InsetDecoration(this));  << this line android studio will have a compiler error as the title. 

How to fix it? thanks .

i don't know kolin BTW.

**Comment by ch4vi** [comment]
Hi! sorry for the delay.
I had to remember my old java skills to find the solution. InsetDecoration is an inner Kotlin class, to convert to Java you have to import explicitly the InsetDecoration class:
`import com.ch4vi.flowlayoutmanager.FlowLayoutManager.InsetDecoration;`

and then create the object like:
`mRecyclerView.addItemDecoration(flowLayoutManager.new InsetDecoration(this));`

but I strongly recommend you learn Kotlin, it's amazing!!
