### ISSUE TITLE
using FlowLayout in java code

### ISSUE THREAD

**Issue by azimot** [ch4vi/FlowLayout#2]
how can i to use this good lib in java code 

FlowLayoutManager layoutManager=new FlowLayoutManager(3, RecyclerView.HORIZONTAL, new FlowLayoutManager.Interface() {
                @Override
                public kotlin.Pair<Integer, Integer> getProportionalSizeForChild(int i) {
                    return null;
                }
            });

it wants kotlin.Pair Object but can not to find it , even i use android.support.v4.util.Pair but is not compatible
how can i to resolve it to using this lib in a java code ?

**Comment by ch4vi** [comment]
I never used my lib with Java. 

I just created a new java project in Android Studio and I can use kotlin.Pair. Try to install the Kotlin plugin in your IDE, you don't have to import anything or add any line in your gradle, Android Studio or Intellij will do the job.

![flow_java](https://cloud.githubusercontent.com/assets/6799011/21608346/3d9d6896-d1bc-11e6-9636-c79e9a12603e.png)

Please tell me if it works ;)

**Comment by azimot** [comment]
i installed kotlin plugin but can not to use kotlin library in java code.
i tried to decompile it and resolving of Object dependency to java .
but after some hours i understand decompiler is not working correctly.
 so i using to make  java version of FlowLayoutManager.kt but syntax is very painful , cause of i'm not kotlin and functional programmer . it's take me long of day 

i searched a lot to find exact library to working like as Flow Layout Concept just this lib have working by RecyclerView and  according to Gifs demo it's perfect 

i see FlowLayoutManager.kt is main class file , is possible for you to release java version please ?

**Comment by ch4vi** [comment]
I'm sorry, to translate Java to Kotlin is easy, but Kotlin to Java could be a pain in the ***, the furthest that I can go is I created a new project and I built a Java version of the sample importing FlowLayout with gradle. If you have the Kotlin plugin installed I think that you should not have problems compiling it.

[MyApplication.zip](https://github.com/ch4vi/FlowLayout/files/687285/MyApplication.zip)
